name: 'Discord Notification'
description: 'Sends a notification to Discord via a webhook'
author: 'insprac'
inputs:
  webhook-url:
    description: 'Your Discord webhook URL'
  title:
    description: 'The notification title'
  message:
    description: 'The notification message body'
  color:
    description: 'The notification color'
runs:
  using: 'node12'
  main: 'dist/index.js'
